name 'awesome_customers'
maintainer 'Sahil Sehgal'
maintainer_email 'sahil.sehgal81@gmail.com'
license 'all_rights'
description 'Installs/Configures awesome_customers'
long_description 'Installs/Configures awesome_customers'
version '0.3.0'

depends 'httpd', '~> 0.2.18'
depends 'iptables','~> 1.0.0'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'mysql', '~> 6.0.17'
depends 'database', '~> 4.0.3'
